USE straviadb;

ALTER TABLE USUARIO_EN_GRUPO
ALTER COLUMN id_usuario VARCHAR(15);

ALTER TABLE USUARIO_EN_RETO
ALTER COLUMN id_usuario VARCHAR(15);

ALTER TABLE USUARIO_SIGUE_USUARIO
ALTER COLUMN id_user VARCHAR(15);

ALTER TABLE USUARIO_SIGUE_USUARIO
ALTER COLUMN user_sigue VARCHAR(15);