USE straviadb;
/*Integridad referencial para relaciones 1:N y 1:N
ALTER TABLE USUARIO
	ADD CONSTRAINT USUARIO_ROL_DEF_FK FOREIGN KEY(id_rol)
		REFERENCES ROL(id)

ALTER TABLE USUARIO
	ADD CONSTRAINT USUARIO_CARRERA_FK FOREIGN KEY(id_carrera)
		REFERENCES CARRERA(id)

ALTER TABLE ACTIVIDAD
	ADD CONSTRAINT ACTIVIDAD_RETO_FK FOREIGN KEY(id_reto)
		REFERENCES RETO(id)

ALTER TABLE ACTIVIDAD
	ADD CONSTRAINT ACTIVIDAD_USUARIO_FK FOREIGN KEY(id_usuario)
		REFERENCES USUARIO(usuario)

ALTER TABLE CARRERA
	ADD CONSTRAINT CARRERA_ACTIVIDAD_FK FOREIGN KEY(id_actividad)
		REFERENCES ACTIVIDAD(id)

ALTER TABLE GRUPO
	ADD CONSTRAINT GRUPO_ADMIN_FK FOREIGN KEY(id_admin)
		REFERENCES USUARIO(usuario)

ALTER TABLE GRUPO
	ADD CONSTRAINT GRUPO_CARRERA_FK FOREIGN KEY(id_carrera)
		REFERENCES CARRERA(id)

ALTER TABLE PAGOCARRERA
	ADD CONSTRAINT PAGOCARRERA_CARRERA_FK FOREIGN KEY(id_carrera)
		REFERENCES CARRERA(id)
*/
/*Integridad referencial para multivaluados
ALTER TABLE CATEGORIAS
	ADD CONSTRAINT CATEGORIAS_CARRERA_FK FOREIGN KEY(id)
		REFERENCES CARRERA(id)

ALTER TABLE CUENTA_BANCARIA
	ADD CONSTRAINT CUENTA_BANCARIA_CARRERA_FK FOREIGN KEY(id)
		REFERENCES CARRERA(id)
*/
/*Integridad referencial de N:M

ALTER TABLE GRUPO_VE_CARRERA
	ADD CONSTRAINT GRUPO_VE_CARRERA_CARRERA_FK FOREIGN KEY(id_carrera)
		REFERENCES CARRERA(id)

ALTER TABLE GRUPO_VE_CARRERA
	ADD CONSTRAINT GRUPO_VE_CARRERA_GRUPO_FK FOREIGN KEY(id_grupo)
		REFERENCES GRUPO(id)

ALTER TABLE GRUPO_VE_RETO
	ADD CONSTRAINT GRUPO_VE_RETO_RETO_FK FOREIGN KEY(id_reto)
		REFERENCES RETO(id)

ALTER TABLE GRUPO_VE_RETO
	ADD CONSTRAINT GRUPO_VE_RETO_GRUPO_FK FOREIGN KEY(id_grupo)
		REFERENCES GRUPO(id)

ALTER TABLE PATROCINA_CARRERA
	ADD CONSTRAINT PATROCINA_CARRERA_CARRERA_FK FOREIGN KEY(id_carrera)
		REFERENCES CARRERA(id)

ALTER TABLE PATROCINA_CARRERA
	ADD CONSTRAINT PATROCINA_CARRERA_PATRON_FK FOREIGN KEY(id_patron)
		REFERENCES PATROCINADOR(id)

ALTER TABLE PATROCINA_RETO
	ADD CONSTRAINT PATROCINA_RETO_RETO_FK FOREIGN KEY(id_reto)
		REFERENCES RETO(id)

ALTER TABLE PATROCINA_RETO
	ADD CONSTRAINT PATROCINA_RETO_PATRON_FK FOREIGN KEY(id_patron)
		REFERENCES PATROCINADOR(id)

ALTER TABLE USUARIO_EN_GRUPO
	ADD CONSTRAINT USUARIO_EN_GRUPO_USUARIO_FK FOREIGN KEY(id_usuario)
		REFERENCES USUARIO(usuario)

ALTER TABLE USUARIO_EN_GRUPO
	ADD CONSTRAINT USUARIO_EN_GRUPO_GRUPO_FK FOREIGN KEY(id_grupo)
		REFERENCES GRUPO(id)

ALTER TABLE USUARIO_EN_RETO
	ADD CONSTRAINT USUARIO_EN_RETO_USUARIO_FK FOREIGN KEY(id_usuario)
		REFERENCES USUARIO(usuario)

ALTER TABLE USUARIO_EN_RETO
	ADD CONSTRAINT USUARIO_EN_RETO_RETO_FK FOREIGN KEY(id_reto)
		REFERENCES RETO(id)

ALTER TABLE USUARIO_SIGUE_USUARIO
	ADD CONSTRAINT USUARIO_SIGUE_USUARIO_USER_FK FOREIGN KEY(id_user)
		REFERENCES USUARIO(usuario)

ALTER TABLE USUARIO_SIGUE_USUARIO
	ADD CONSTRAINT USUARIO_SIGUE_USUARIO_SEGUIDO_FK FOREIGN KEY(user_sigue)
		REFERENCES USUARIO(usuario)
*/