USE straviadb;
CREATE TABLE USUARIO_EN_GRUPO(
	id_usuario VARCHAR(20) NOT NULL,
	id_grupo INT NOT NULL,
	PRIMARY KEY (id_usuario, id_grupo)
	/* CONSTRAINT USUARIO_EN_GRUPO_USER FOREIGN KEY (id_usuario) REFERENCES USUARIO(usuario),
	CONSTRAINT USUARIO_EN_GRUPO_GRUPO FOREIGN KEY (id_grupo) REFERENCES GRUPO(id),
	CONSTRAINT USUARIO_EN_GRUPO_UNIQUE UNIQUE (id_usuario, id_grupo)*/
	);

CREATE TABLE USUARIO_SIGUE_USUARIO(
	id_user VARCHAR(20) NOT NULL,
	user_sigue VARCHAR(20) NOT NULL,
	PRIMARY KEY(id_user, user_sigue)
	/*CONSTRAINT USUARIO_SIGUE_USUARIO FOREIGN KEY (id_user) REFERENCES USUARIO(usuario),
	CONSTRAINT USUARIO_SIGUE_USUARIO FOREIGN KEY (user_sigue) REFERENCES USUARIO(usuario),
	CONSTRAINT USUARIO_SIGUE_USUARIO UNIQUE (id_usuario, id_grupo)*/
	);

CREATE TABLE USUARIO_EN_RETO(
	id_usuario VARCHAR(20) NOT NULL,
	id_reto INT NOT NULL,
	PRIMARY KEY (id_usuario, id_reto));