USE straviadb;

/*
ESTE TRIGGER AGREGA EL ADMIN DE UN GRUPO COMO 
USUARIO MIEMBRO TAMBIÉN DEL MISMO GRUPO EN LA TABLA
USUARIO_EN_GRUPO, DE OTRA FORMA NO PODRÍA VER LAS 
CARRERAS Y RETOS DE SU GRUPO
*/
CREATE TRIGGER  tr_nuevo_miembro_de_grupo
ON GRUPO
FOR UPDATE, INSERT
AS
BEGIN
SET NOCOUNT ON;
BEGIN
INSERT INTO USUARIO_EN_GRUPO(id_usuario, id_grupo)
SELECT id_admin, id FROM inserted
END
END
drop trigger tr_nuevo_miembro_de_grupo